//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tutorial_7___TellyMate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tutorial_7___TellyMate.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       _       _
        ///     (_\     /_)
        ///       ))   ((
        ///     .-&quot;&quot;&quot;&quot;&quot;&quot;&quot;-.  
        /// /^\/  _.   _.  \/^\
        /// \(   /__\ /__\   )/
        ///  \,  \o_/_\o_/  ,/
        ///    \    (_)    /
        ///     `-.&apos;===&apos;.-&apos;
        ///      __) - (__   
        ///     /  `~~~`  \
        ///    /  /     \  \
        ///    \ :       ; /
        ///     \|==(*)==|/
        ///      :       :
        ///       \  |  /
        ///     ___)=|=(___
        ///    {____/ \____} 
        ///
        ///.
        /// </summary>
        internal static string Alien {
            get {
                return ResourceManager.GetString("Alien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ____  ____     ____ 
        ///( ___)(_   )___(  _ \
        /// )__)  / /_(___)) _ &lt;
        ///(____)(____)   (____/
        ///
        /// ____  _____  ___  _  _  ___ 
        ///(  _ \(  _  )/ __)( )/ )/ __)
        /// )   / )(_)(( (__  )  ( \__ \
        ///(_)\_)(_____)\___)(_)\_)(___/
        ///
        ///.
        /// </summary>
        internal static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to        _n____n__
        ///     /         \---||--&lt;
        ///    /___________\
        ///    _|____|____|_
        ///    _|____|____|_
        ///     |    |    |
        ///    --------------
        ///    | || || || ||\
        ///    | || || || || \++++++++------&lt;
        ///    ===============
        ///    |   |  |  |   |
        ///   (| O | O| O| O |)
        ///   |   |   |   |   |
        ///  (| O | O | O | O |)
        ///   |   |   |   |    |
        /// (| O |  O | O  | O |)
        ///  |   |    |    |    |
        /// (| O |  O |  O |  O |)
        /// ======================
        ///.
        /// </summary>
        internal static string Dalek {
            get {
                return ResourceManager.GetString("Dalek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EEEEEE ZZZZZ      BBBB
        ///E          Z      B   B
        ///E         Z       B   B
        ///EEEE     Z   ---- BBBB
        ///E       Z         B   B
        ///E      Z          B   B
        ///EEEEEE ZZZZZ      BBBB
        ///
        ///.
        /// </summary>
        internal static string EZB {
            get {
                return ResourceManager.GetString("EZB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EEEE ZZZZZ     BBBB  
        ///E       Z      B   B 
        ///EEE    Z   --- BBBB  
        ///E     Z        B   B 
        ///EEEE ZZZZZ     BBBB  
        ///
        ///RRRR   OOO   CCC K  K  SSS  
        ///R   R O   O C    K K  S     
        ///RRRR  O   O C    KK    SSS  
        ///R R   O   O C    K K      S 
        ///R  RR  OOO   CCC K  K SSSS  
        ///.
        /// </summary>
        internal static string EZB_Rocks {
            get {
                return ResourceManager.GetString("EZB_Rocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   ______ ______      ____  
        /// |  ____|___  /     |  _ \ 
        /// | |__     / /______| |_) |
        /// |  __|   / /|______|  _ &lt; 
        /// | |____ / /__      | |_) |
        /// |______/_____|     |____/ 
        ///                           
        ///                           
        ///
        ///  _____   ____   _____ _  __ _____ 
        /// |  __ \ / __ \ / ____| |/ // ____|
        /// | |__) | |  | | |    | &apos; /| (___  
        /// |  _  /| |  | | |    |  &lt;  \___ \ 
        /// | | \ \| |__| | |____| . \ ____) |
        /// |_|  \_\\____/ \_____|_|\_\_____/ 
        ///.
        /// </summary>
        internal static string EZB3D {
            get {
                return ResourceManager.GetString("EZB3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///          ,     ,
        ///         (\____/)
        ///          (_oo_)
        ///            (O)
        ///          __||__    \)
        ///       []/______\[] /
        ///       / \______/ \/
        ///      /    /__\
        ///     (\   /____\
        ///          ||  ||
        ///          ||  ||
        ///        __||  ||__
        ///============================
        ///.
        /// </summary>
        internal static string Robot1 {
            get {
                return ResourceManager.GetString("Robot1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                .,,: ,.
        ///           .-:++++XXXXXX
        ///         .,:+++XXXXXXXXXXX
        ///        .++:++XXXXXXXXXX@XX
        ///       .++:+++XXX+++X+XXXXXXX
        ///       ,+::+:::.-----++++XXXX
        ///      .-::+ .-&apos;       .XX@++X@
        ///      .,:::|      .-.  |+@X+XXM
        ///       ,:-:| .-&apos;       |+XX+XXM
        ///       ==-::\    _.    &apos;.X+XXX@
        ///       -:+:::\          |XXX@X@
        ///       ..:+++:\  --&apos;   .XXXX@X@M
        ///         .:+:++&apos;.____.|+XXX@@@@MMM
        ///           ,-:+:+\     \+X++:+++XXM
        ///       ____=:++++/      |-,,/     :\
        ///      . /-.              /,/       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Woman {
            get {
                return ResourceManager.GetString("Woman", resourceCulture);
            }
        }
    }
}
